services:
  football-app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./app:/app/app  # Permite Hot Reload (edita no VS Code e atualiza no browser)
      